title: GitHub Desktop Features
author: Ashwin Kumar
email: techgod2001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here, we will describe the various features provided by the GUI version of Git called GitHub Desktop.

# social links
twitter_username: NotIncluded # DO NOT include the @ character, or else the build will fail!
github_username:  AshwinKumar2001 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
